name: Generate Fedora Spec for COPR

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "pkg/fedora-spec/*.spec"

jobs:
  generate-spec:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
      - name: Verify yq installation
        run: yq --version
      - name: Install rpmlint
        run: sudo apt-get install -y rpmlint
      - name: Generate spec files
        run: ./pkg/bin/generate_spec.sh
        env:
          GHA_RUN_NUMBER: ${{ github.run_number }}
          GHA_SHA: ${{ github.sha }}
          GHA_REF: ${{ github.ref }}
      - name: Validate generated spec files
        run: |
          for spec_file in pkg/fedora-spec/*.spec; do
            echo "Validating $spec_file"
            rpmlint $spec_file || exit 1
          done
      - name: Commit spec files to PR branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add pkg/fedora-spec/*.spec
          git diff --staged --quiet || git commit -m "chore: Update spec files"
          git push
